version: "2"

services:
  elasticsearch:
    image: elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch_data/:/usr/share/elasticsearch/data
    mem_limit: "1g"

  logstash-agent:
    build:
      context: ./logstash-agent
      dockerfile: Dockerfile
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp

  kibana:
    image: kibana:7.11.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch


# sudo docker exec -u 0 56c296a937b0 chown 1000:1000 /usr/share/elasticsearch/data